version: "3.9"
services:
  apiserver:
    build:
      context: .
      dockerfile: Dockerfile.apiserver
    ports:
      - "8080:8080"
    environment:
      - AWS_REGION=ap-southeast-1
      - AWS_ACCESS_KEY_ID=AKIAUR32DTPFVSEKUZCX
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_S3_BUCKET_NAME=simplestore.newzealot.com
      - AWS_S3_URL_PREFIX=https://s3-ap-southeast-1.amazonaws.com/simplestore.newzealot.com/
      - AWS_COGNITO_USER_POOL_ID=ap-southeast-1_mAeiHVzJW
      - AWS_COGNITO_APP_CLIENT_ID=7tump4lnb2k48d8fj97kbea7a3
      - AWS_MYSQL_USERNAME=simplestoreadmin
      - AWS_MYSQL_PASSWORD=IeBAW4n1379230B02ZBC
      - AWS_MYSQL_DBNAME=simplestore
      - AWS_MYSQL_ENDPOINT=simplestore.c34ps049slmi.ap-southeast-1.rds.amazonaws.com
      - APISERVER=http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:8080
      - WEBSERVER=http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:5000
      - STRIPE_PUBLIC_KEY=pk_test_51IpP7FLR7Al1f4KyC1mHheiOA1blBeFdAD5B1kkmwtCqccoDGPlpyrqUb9hRIAhIgDo0EEjBTZzXVaS0yzlO0qva00Bu03Y9wb
      - STRIPE_SECRET_KEY=sk_test_51IpP7FLR7Al1f4KySKyLk0jkMQceN9knDS4Qx3bcZc0x69JbrOIXjzoOdI1PjhrnIaYrioNa5tPCpvJSlAHJQiSx00WwcPPmUY
  webserver:
    build:
      context: .
      dockerfile: Dockerfile.webserver
    ports:
      - "5000:5000"
    environment:
      - AWS_REGION=ap-southeast-1
      - AWS_ACCESS_KEY_ID=AKIAUR32DTPFVSEKUZCX
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_S3_BUCKET_NAME=simplestore.newzealot.com
      - AWS_S3_URL_PREFIX=https://s3-ap-southeast-1.amazonaws.com/simplestore.newzealot.com/
      - AWS_COGNITO_USER_POOL_ID=ap-southeast-1_mAeiHVzJW
      - AWS_COGNITO_APP_CLIENT_ID=7tump4lnb2k48d8fj97kbea7a3
      - AWS_MYSQL_USERNAME=simplestoreadmin
      - AWS_MYSQL_PASSWORD=IeBAW4n1379230B02ZBC
      - AWS_MYSQL_DBNAME=simplestore
      - AWS_MYSQL_ENDPOINT=simplestore.c34ps049slmi.ap-southeast-1.rds.amazonaws.com
      - APISERVER=http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:8080
      - WEBSERVER=http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:5000
      - STRIPE_PUBLIC_KEY=pk_test_51IpP7FLR7Al1f4KyC1mHheiOA1blBeFdAD5B1kkmwtCqccoDGPlpyrqUb9hRIAhIgDo0EEjBTZzXVaS0yzlO0qva00Bu03Y9wb
      - STRIPE_SECRET_KEY=sk_test_51IpP7FLR7Al1f4KySKyLk0jkMQceN9knDS4Qx3bcZc0x69JbrOIXjzoOdI1PjhrnIaYrioNa5tPCpvJSlAHJQiSx00WwcPPmUY
